name: Deploy server

on:
  push:
    branches:
      - "develop"

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'gradle'
      - run: ./gradlew jar

      - name: Copy TPL files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./tools/www-tpl"
          target: ${{ secrets.TPL_PATH }}
          strip_components: 3

      - name: Copy Web
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./Havana-Web/build/libs/*.jar"
          target: ${{ secrets.SERVER_PATH }}
          strip_components: 3

      - name: Copy Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./Havana-Server/build/libs/*.jar"
          target: ${{ secrets.SERVER_PATH }}
          strip_components: 3